[env]
KUBECONFIG = '{{config_root}}/kubeconfig'
MINIJINJA_CONFIG_FILE = '{{config_root}}/.minijinja.toml'
SOPS_AGE_KEY_FILE = '{{config_root}}/age.key'
TALOSCONFIG = '{{config_root}}/talosconfig'
JUST_UNSTABLE = '1'
LEFTHOOK_OUTPUT = 'false'

[tools]
'1password' = 'latest'
'age' = 'latest'
'flux2' = 'latest'
'github-cli' = 'latest'
'gum' = 'latest'
'helm' = 'latest'
'helmfile' = 'latest'
'jq' = 'latest'
'just' = 'latest'
'krew' = 'latest'
'kubectl' = 'latest'
'kustomize' = 'latest'
'sops' = 'latest'
'talos' = 'latest'
'uv' = 'latest'
'yq' = 'latest'
'pipx:flux-local' = 'latest'
