---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pihole-dns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: pihole-dns-secret
    template:
      data:
        EXTERNAL_DNS_PIHOLE_PASSWORD: '{{ .PIHOLE_PASSWORD }}'
  dataFrom:
    - extract:
        key: pihole
