---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app pihole-dns
spec:
  chartRef:
    kind: OCIRepository
    name: pihole-dns
  interval: 1h
  values:
    fullnameOverride: *app
    provider:
      name: pihole
    env:
      - name: EXTERNAL_DNS_PIHOLE_SERVER
        value: http://10.30.0.10
      - name: &name EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: &secret pihole-dns-secret
            key: *name
    registry: noop
    triggerLoopEvent: true
    policy: upsert-only
    sources:
      - gateway-httproute
      - service
    domainFilters:
      - mordex.io
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
